"""initial schema from schema.sql

Revision ID: e2033655ad3b
Revises: 
Create Date: 2026-07-19 14:56:04.137740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2033655ad3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocr_jobs')
    op.drop_index(op.f('idx_corr_log_job'), table_name='corrections_log')
    op.drop_index(op.f('idx_corr_log_label'), table_name='corrections_log')
    op.drop_index(op.f('idx_corr_log_time'), table_name='corrections_log')
    op.drop_table('corrections_log')
    op.add_column('ocr_documents', sa.Column('ambiguous_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ocr_documents', sa.Column('relationship_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('ocr_documents', 'processing_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('ocr_documents', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('ocr_documents', 'num_pdfs',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('ocr_documents', 'result_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('ocr_documents', 'government_id_verified',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('ocr_documents', 'type_of_home',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('ocr_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ocr_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_ocr_documents_result_json_job_id'), table_name='ocr_documents')
    op.create_unique_constraint(None, 'ocr_documents', ['file_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ocr_documents', type_='unique')
    op.create_index(op.f('idx_ocr_documents_result_json_job_id'), 'ocr_documents', [sa.literal_column("(result_json ->> 'job_id'::text)")], unique=False)
    op.alter_column('ocr_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ocr_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ocr_documents', 'type_of_home',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('ocr_documents', 'government_id_verified',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ocr_documents', 'result_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('ocr_documents', 'num_pdfs',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('ocr_documents', 'confidence_score',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('ocr_documents', 'processing_time',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('ocr_documents', 'relationship_details')
    op.drop_column('ocr_documents', 'ambiguous_fields')
    op.create_table('corrections_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('field_label', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('original_value', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('corrected_value', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('pdf_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('edited_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('corrections_log_pkey'))
    )
    op.create_index(op.f('idx_corr_log_time'), 'corrections_log', ['edited_at'], unique=False)
    op.create_index(op.f('idx_corr_log_label'), 'corrections_log', ['field_label'], unique=False)
    op.create_index(op.f('idx_corr_log_job'), 'corrections_log', ['job_id'], unique=False)
    op.create_table('ocr_jobs',
    sa.Column('job_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'submitted'::text"), autoincrement=False, nullable=False),
    sa.Column('datalab_request_id', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('datalab_check_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('file_hash', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('error_detail', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("status = ANY (ARRAY['submitted'::text, 'collecting'::text, 'completed'::text, 'failed'::text])", name=op.f('ocr_jobs_status_check')),
    sa.PrimaryKeyConstraint('job_id', name=op.f('ocr_jobs_pkey'))
    )
    # ### end Alembic commands ###
